# Generated by Django 5.2.14 on 2026-06-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('requiere_token', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='app.especialidad')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico', to=settings.AUTH_USER_MODEL)),
                ('obras_sociales', models.ManyToManyField(blank=True, related_name='medicos_que_la_aceptan', to='app.obrasocial')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.obrasocial')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas', to='app.medico')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='franja_hora_fin_mayor_inicio')],
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='app.medico')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='fecha_fin_mayor_igual_inicio')],
            },
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('nombre', ''), _negated=True), name='paciente_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('apellido', ''), _negated=True), name='paciente_apellido_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('dni', ''), _negated=True), name='paciente_dni_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('telefono', ''), _negated=True), name='paciente_telefono_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='paciente_email_no_vacio'),
        ),
    ]
