# Generated by Django 5.2.14 on 2026-06-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_especialidad_alter_medico_especialidad'),
        ('app', '0002_obrasocial_paciente'),
    ]

    operations = [
    ]
