# Generated by Django 5.2.14 on 2026-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_turno_ausencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.RemoveField(
            model_name='obrasocial',
            name='medico',
        ),
        migrations.AddField(
            model_name='medico',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, related_name='medicos_que_la_aceptan', to='app.obrasocial'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
