# Generated by Django 5.1.15 on 2026-06-24 01:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_turno_ausencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha_hora']},
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='fecha',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='paciente_apellido',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='paciente_nombre',
        ),
        migrations.AddField(
            model_name='turno',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo',
            field=models.TextField(default='Sin motivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
