# Generated by Django 5.1.15 on 2026-06-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_turno_options_rename_fecha_turno_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='hora_fin',
            field=models.TimeField(default='17:00', help_text='Hora de fin de la jornada laboral (formato HH:MM)'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_inicio',
            field=models.TimeField(default='09:00', help_text='Hora de inicio de la jornada laboral (formato HH:MM)'),
        ),
    ]
"#"  
